spring:
  flyway:
    url: jdbc:postgresql://localhost:5433/rxdemo
    user: postgres
    password: postgres
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/rxdemo
    username: postgres
    password: postgres
